language: node_js
node_js:
- '0.12'
deploy:
  provider: heroku
  api_key:
    secure: kPQbbDBZTUCdG27mZkz4U6cWbr9ggv8rGzpys403LpnMgB7N4bImkUJKFD5DpyjzMr7L9Xnj6JswMqTyJ5NqbiHftzqWmrQS35WzRt4fd28EYNtBr7LGiQog233ODOeFrpOTM7iFJ9UqlxsjRlIytetHfBU1aQbF/7desemQItt5VmX35OtaPdaCLDVI6GXsqpWXNth+a/JnCnkB1eFrEBkedB6YI2OfWe16vvERzgzl4iaKEx7PBjRHZ6xqHX2Tm9tPjein4jE6cJDapeXtNHB5927BdK07XPwTz8ufjzQt9ysOG10R7FppKXTmq0re28Tu7lQcc65gtC86Eoy6/zqGcSd7TLd05elo9/HlaM/6qs6FfQVesZ8LiUMoixytC5mIzkcqRISm2gK7qiZsEbFZnCS8R8Utw3bcuIkjrfHWKDWuxYxMsjwtYthPsk+WF6LY4zfeXBObsAzl5VDSlxuhy9DrSW093x+anxVfS+hK6E0qCHhCFb7KneZNurLBmZNbPRuk/Crv5jW3Ud8zN1QId7sv6jVMGl0LXTBVxKkxWDQlU5S2bqvuxIDIj5PqdXR0AmXKDtqXws4F6Nun+5eXfe71ERC60JxL3V9Znjt7UWNDoyJfS9QC/wrDj7wJvpaIwqKNlM8l33uI+CmxBzFo2ev1A8TZNulnR16d+co=
  app: tl-18f
  on:
    repo: TeraLogics/18F
  run:
    - "npm install"
    - restart