language: node_js
node_js:
- '0.12'
before_install: make clobber
script: make ci-travis
after_success: make submit-cov
deploy:
  provider: heroku
  api_key:
    secure: kPQbbDBZTUCdG27mZkz4U6cWbr9ggv8rGzpys403LpnMgB7N4bImkUJKFD5DpyjzMr7L9Xnj6JswMqTyJ5NqbiHftzqWmrQS35WzRt4fd28EYNtBr7LGiQog233ODOeFrpOTM7iFJ9UqlxsjRlIytetHfBU1aQbF/7desemQItt5VmX35OtaPdaCLDVI6GXsqpWXNth+a/JnCnkB1eFrEBkedB6YI2OfWe16vvERzgzl4iaKEx7PBjRHZ6xqHX2Tm9tPjein4jE6cJDapeXtNHB5927BdK07XPwTz8ufjzQt9ysOG10R7FppKXTmq0re28Tu7lQcc65gtC86Eoy6/zqGcSd7TLd05elo9/HlaM/6qs6FfQVesZ8LiUMoixytC5mIzkcqRISm2gK7qiZsEbFZnCS8R8Utw3bcuIkjrfHWKDWuxYxMsjwtYthPsk+WF6LY4zfeXBObsAzl5VDSlxuhy9DrSW093x+anxVfS+hK6E0qCHhCFb7KneZNurLBmZNbPRuk/Crv5jW3Ud8zN1QId7sv6jVMGl0LXTBVxKkxWDQlU5S2bqvuxIDIj5PqdXR0AmXKDtqXws4F6Nun+5eXfe71ERC60JxL3V9Znjt7UWNDoyJfS9QC/wrDj7wJvpaIwqKNlM8l33uI+CmxBzFo2ev1A8TZNulnR16d+co=
  app:
    master: total-briecall
    development: total-briecall-dev
  run:
  - npm install --global apidoc
  - npm run apidoc
  - restart
notifications:
  slack:
    secure: RUOKymOPw0u47KLieUV8UUP9A74kAk5wKoQe+B7g64ZRgHUfq354t6ghqy8w11aqhwHibOxD8fjky/sJH39fypWKkJKIY9NiTOVE5ZFK2FwbQHJjRbGt538P0UQfD/2d7/hR9ImIvbMNMFPDoUpNHGK59vjLK+Brplk50FQXCmN3kRyh6bs/kwgPaNGnAVq+AeD9DX1q9ZTUnPeJdCVV3uf5ovjk+9dPVNQbYHMdgAfUd/BSKdcggdS8nQNOJG69OL8NB/8nF//yjj3xkKLifRfr5KXuTgK80Cb4gv2X/0GytRzV+Tt9TvMvkto1zxOm+zooyE3v5OFwIqw2G4Acwta9WfYwBJOoFdCEBxXGw+a98swp6lfsxdLXkaFpCjsgeb8BlIrwx6eQxXHOh6iUk6oinossE0+GklsRoMkO2BuNCEzW+mZRli3wptud1pD0RguHqFVqVEFEMz4GD46sC+Z9l5AIpgfceR1nVGtwK1kINa66eMqy6HosnpaE7ITHquzamyjpqFpG/fFHyF+LXHr3UmbA0j5/xtraRoDQlM2oBIEj1rQaaiSeIbMpQ+ppu0rZJM85hDcSWWgTeym2ny0k/bmvTGV0xie6bHfN4tsSXiqlx/LnoPkeZ9Pu5ikGUFenXWgMOX1LIdO7PUGRnSJWVSB6fxdj2vkXDMx6gCo=